apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: call-ansible-job-pre
spec:
  extra_vars:
    data: "This job was called as part of the pre_hook deployment of appgeneric"
  job_template_name: acm-hook
  tower_auth_secret: controller-admin

